import 'package:cloud_firestore/cloud_firestore.dart';

///This is a custom model for the Address
///In this model it has parameters like
///
///1. id
///
///2. name
///
///3. street
///
///4. city
///
///5. state
///
///6. postalCode
///
///7. phoneNumber
///
///8. address
///
///This model is used to store the address details of the user
///It is used in the address controller to store the address details
///The ID for the address is generated by the `address type` and the current date time
///This model is also used to store the address details in the firestore
///It is also used to fetch the address details from the firestore
class AddressModel {
  String id;
  String name;
  String street;
  String city;
  String state;
  String postalCode;
  String phoneNumber;
  String address;
  String type;

  AddressModel({
    required this.id,
    required this.name,
    required this.street,
    required this.type,
    required this.city,
    required this.state,
    required this.postalCode,
    required this.phoneNumber,
    required this.address,
  });

  static AddressModel fromSnapshot(
      QueryDocumentSnapshot<Map<String, dynamic>> document) {
    return AddressModel(
      id: document.id,
      address: document['address'],
      name: document['name'],
      street: document['street'],
      type: document['type'],
      city: document['city'],
      state: document['state'],
      postalCode: document['postalCode'],
      phoneNumber: document['phoneNumber'],
    );
  }

  static AddressModel get empty => AddressModel(
        id: '',
        name: '',
        street: '',
        type: '',
        city: '',
        state: '',
        postalCode: '',
        phoneNumber: '',
        address: '',
      );

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'street': street,
      'city': city,
      'state': state,
      'postalCode': postalCode,
      'type': type,
      "address": address,
      'phoneNumber': phoneNumber,
    };
  }
}
